### ISSUE TITLE
ESVP API Documentation

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ESV-Server#3]
Maybe it's still early days and I'm jumping the gun as they say, but are there more API routes and documentation other than what is specified here: https://github.com/usnistgov/ESV-Server/blob/main/Entropy%20Source%20Validation%20Protocol.md

Maybe I'm just looking in the wrong place.

I'm guessing that it will follow a similar pattern to ACVP, but I don't see any documentation about reading the status of a registered entropy source, or finding out the verdict/result of the analysis, etc...

**Comment by smuellerDD** [comment]
Hey Alex, the project is just being born and you expect it being already dancing? :-)

**Comment by AlexThurston** [comment]
Hehe!  I guess I'm all dressed up with my dancing shoes on my feet.

Truth be told, I thought that maybe the API documentation got moved when they moved to https://pages.nist.gov and I wasn't seeing it.

**Comment by celic** [comment]
We have some additional endpoints (Certify and Status of a dataFile). The Certify doesn't do anything now as this is Demo, but the Status, do a GET on the URL you posted a file to in order to see the run status and results when completed. I can add that to the documentation.

The scope of the project is less than ACVP, intentionally. No need to reinvent the endpoints used to collect metadata.

**Comment by celic** [comment]
In terms of verdict/result of analysis, there are a couple of other systems in play that we need to integrate with. We can build a package to submit to a reviewer, but CMVP has a couple different tools used to perform the reviews. We would like to utilize those rather than creating a new interface. So expect this to create a ticket within Resolve or something along those lines.
